### ISSUE TITLE
takeNodesSnapshot - page.evaluate: TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by Querela** [webis-de/scriptor#11]
Possible error, not sure how it was raised exactly.

URL: https://lotustl.com/im/immortal-v4c72-zhong-shan-uses-a-sword-to-release-the-blade/?utm_source=rss&utm_medium=rss&utm_campaign=immortal-v4c72-zhong-shan-uses-a-sword-to-release-the-blade

```js
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

page.evaluate: TypeError: Cannot read properties of undefined (reading 'id')
    at traverse (eval at evaluate (:3:2389), <anonymous>:25:27)
    at eval (eval at evaluate (:3:2389), <anonymous>:86:5)
    at t.default.evaluate (<anonymous>:3:2412)
    at t.default.<anonymous> (<anonymous>:1:44)
    at takeNodesSnapshot (/scriptor/lib/pages.js:337:36)
    at Object.takeSnapshot (/scriptor/lib/pages.js:258:25)
    at module.exports._processOne (/script/Script-multi.js:115:19)
    at async module.exports.run (/script/Script-multi.js:54:24)
    at async Object.run (/scriptor/lib/scripts.js:64:31)
```

_Note: I may need to run this URL on its own with the default Script to check reproducibility later._

And the curious thing is that I have wrapped the call of `await pages.takeSnapshot(page, optionsSnapshot);` in `try { } catch (error) { }` and it still killed my process.

**Comment by johanneskiesel** [comment]
According to the error message, `node` would be `undefined` in this line: https://github.com/webis-de/scriptor/blob/0cf173291b6022c992d3c3060d40bff7223b251a/lib/pages.js#L361

And this seems to have happened in the first loop of the recursion... which would mean the document has no "body" element?

I see a body element when I open the page in the browser, but maybe they have some crawl protection that does weird stuff. It is probably a good idea to just check whether `node` is undefined.

With regard to the catch, I think the proper way would be:
```
await pages.takeSnapshot(page, optionsSnapshot).catch(error => {});
```

**Comment by johanneskiesel** [comment]
I added this check now as part of scriptor v0.6.4. Please check. Not sure if there are other ways to handle this, though?

**Comment by Querela** [comment]
Probably not? I can't think of another way of handling this that will still allow the NodesSnapshot to complete.
I think for single URLs, it is ok for the default script to fail early. It is more a problem if someone (like me) _chains_ lots of URLs together and processes them with the same container/process. But then the error handling is more my responsibility since I want to handle the errors gracefully and continue with the remaining URLs.

I got another error: (for https://perpetualdaydreams.com/novel/nhad/nhad-32-2/, http://wuxianation.com/eth2/eth-ch-21.html)
```js
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

page.screenshot: Timeout 10000ms exceeded.
    at takeScreenshot (/scriptor/lib/pages.js:450:15)
    at Object.takeSnapshot (/scriptor/lib/pages.js:259:22)
    at module.exports._processOne (/script/Script-multi.js:115:19)
    at async module.exports.run (/script/Script-multi.js:54:24)
    at async Object.run (/scriptor/lib/scripts.js:64:31) {
  name: 'TimeoutError'
}
```
so I really need to add this promise error handling `.catch(error => {});` to my script.

**Comment by johanneskiesel** [comment]
Ok, then I close this.

But note that you can disable the timeout of the screenshot function: https://playwright.dev/docs/api/class-page#page-screenshot

**Comment by Querela** [comment]
> But note that you can disable the timeout of the screenshot function: https://playwright.dev/docs/api/class-page#page-screenshot

Well, the curious thing is that for a lot of larger other pages it worked without issue. I set the timeout in the browser context to 10s. On average the whole page load to screenshot process (with 3s delay) takes around 4-5s. But the error only happened once so far. Just unexpected since the page should have been rendered already, so a screenshot should be almost instant.

**Comment by Querela** [comment]
Update about `takeScreenshot` Timeout errors: They still happen, even with error handling. Not catchable?
```js
try {
      // ...

      // Take snapshot
      await pages.takeSnapshot(page, optionsSnapshot).catch(error => {
        log.error({ err: error, err_msg: error.message.split("\n")[0], id: id, url: url }, "error with snapshotting (promise)");
      });

      return true;
    } catch (error) {
      log.error({ err: error, err_msg: error.message.split("\n")[0], id: id, url: url }, "error with snapshotting");
      return false;
    }
```

**Comment by johanneskiesel** [comment]
Mh, maybe I have to also catch the error inside `pages.takeSnapshot?`

According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch#gotchas_when_throwing_errors : 

> Errors thrown inside asynchronous functions will act like uncaught errors

This probably applies to our case here: https://github.com/webis-de/scriptor/blob/main/lib/pages.js#L446

**Comment by Querela** [comment]
Hmm. Not sure what to do.
For me, I would probably just create a copy of `takeSnapshot` or the others to wrap the errors.

I'm unsure whether `scriptor` wants to fail early when something happens (timeout, ...) or gracefully and just return `null`/`undefined`, and then the user has to check. The issue with fail-early is that it terminates the process which is probably not something useful for anyone who modifies the default script since you can't really recover from it.

I would need to check whether the URLs that timeout do this deterministically. If so, then I might be able to test stuff.

As for the timeouts. I set them to 10 seconds to avoid hanging scripts (which I had even with another `page....` function). But it might be that timeout errors aren't even catchable? Not sure how they bubble ...
[page.screenshot](https://playwright.dev/docs/api/class-page#page-screenshot) [[src](https://github.com/microsoft/playwright/blob/9285596806b0b02a88ca8fe30d4ccc43550c96f9/packages/playwright-core/src/client/page.ts#L456), [src mit timeout controller](https://github.com/microsoft/playwright/blob/9285596806b0b02a88ca8fe30d4ccc43550c96f9/packages/playwright-core/src/server/dom.ts#L758)] / [browserContext.setDefaultTimeout](https://playwright.dev/docs/api/class-browsercontext#browser-context-set-default-timeout)
How to catch (theoretically), according to the docs: https://playwright.dev/docs/api/class-timeouterror
BUT I have my code wrapped with `try { ... } catch (error) { ... }` and it still kills my script/container...

**Comment by johanneskiesel** [comment]
Could you provide a minimal example for the uncatchable error? Perhaps just with a very small timeout?

**Comment by Querela** [comment]
I can try.

**Comment by Querela** [comment]
So, my setup:

<details>
  <summary>Script.js</summary>
  
```js
const fs = require("fs-extra");
const path = require("path");

const { AbstractScriptorScript, files, pages, log } = require("@webis-de/scriptor");

const NAME = "Snapshot-NU";
const VERSION = "0.1.0";

const SCRIPT_OPTION_URLS = "urls";
const SCRIPT_OPTION_URLS_ID = "id";
const SCRIPT_OPTION_URLS_URL = "url";
const SCRIPT_OPTIONS_VIEWPORT_ADJUST = "viewportAdjust";
const SCRIPT_OPTIONS_SNAPSHOT = "snapshot";

module.exports = class extends AbstractScriptorScript {

  constructor() {
    super(NAME, VERSION);
  }

  async run(browserContexts, scriptDirectory, inputDirectory, outputDirectory) {
    const browserContext = browserContexts[files.BROWSER_CONTEXT_DEFAULT];
    // set all timeouts to 10 seconds
    browserContext.setDefaultNavigationTimeout(10000);
    browserContext.setDefaultTimeout(10000);

    // Script options
    const defaultScriptOptions = {
      viewportAdjust: {},
      snapshot: {
        // we just want visibility and maybe id/classes
        nodes: { addElementText: false, addCss: false, addAttributes: false },
        viewport: false,
        // custom, if not `false`, then strip invisible element and save result, too
        domCleaned: Object.freeze({ defaultName: "dom-cleaned.html" })
      },
      failNon2XX: true
    };
    const requiredScriptOptions = [SCRIPT_OPTION_URLS];
    const scriptOptions = files.readOptions(
      files.getExisting(files.SCRIPT_OPTIONS_FILE_NAME, [scriptDirectory, inputDirectory]),
      defaultScriptOptions, requiredScriptOptions
    );
    log.info({ options: scriptOptions }, "script.options");
    fs.writeJsonSync(path.join(outputDirectory, files.SCRIPT_OPTIONS_FILE_NAME), scriptOptions);

    const urls = scriptOptions[SCRIPT_OPTION_URLS];
    log.info("Processing %s urls.", urls.length);

    var errors = 0;
    for (let i = 0; i < urls.length; i++) {
      const url_data = urls[i];
      const page = await browserContext.newPage();
      const no_error = await this._processOne(page, scriptOptions, outputDirectory, url_data);
      if (!no_error) { errors++; }
      await page.close();
    }

    log.info("Processing finished. %s errors for %s urls.", errors, urls.length);

    return true;
  }

  /**
   * Process a single url (load url in page, take snapshot).
   * @param {Page} page - A Playwright {@link https://playwright.dev/docs/api/class-page|Page} object
   * @param {object} scriptOptions - Script options object, for e.g. snapshot-specific options
   * @param {string} outputDirectory - The directory to store the snapshots in (will be created if it does not exist)
   * @param {object} url_data - The URL data (`id` - ID of URL, `url` - URL string)
   * @returns {boolean} - `false` if error occured (timeouts/status code/snapshotting), `true` otherwise
   */
  async _processOne(page, scriptOptions, outputDirectory, url_data) {
    const id = url_data[SCRIPT_OPTION_URLS_ID].toString();
    const url = url_data[SCRIPT_OPTION_URLS_URL];
    log.info({ id: id, url: url }, "snapshot")

    const optionsViewportAdjust = scriptOptions[SCRIPT_OPTIONS_VIEWPORT_ADJUST];

    const optionsSnapshot = Object.assign(
      // nest by extnu_id
      { path: path.join(outputDirectory, "snapshot", id) },
      // lets give them custom file names including the extnu_id
      // {
      //   dom: { path: `${id}.dom.html` },
      //   nodes: { path: `${id}.nodes.jsonl` },
      //   screenshot: { path: `${id}.screenshot.png` },
      // },
      scriptOptions[SCRIPT_OPTIONS_SNAPSHOT]);
    // log.debug({ optionsSnapshot: optionsSnapshot }, "optionsSnapshot");

    try {
      // Load page
      // https://playwright.dev/docs/api/class-page#page-goto
      // waitUntil <"load"|"domcontentloaded"|"networkidle"|"commit">
      const response = await page.goto(url);
      const responseCode = response.status();
      if (responseCode < 200 || responseCode > 299) {
        log.warn({ id: id, url: url, responseCode: responseCode }, "page.goto(url)");
        if (scriptOptions.failNon2XX) {
          return false;
        } else {
          this._writeStatus(optionsSnapshot.path, { status: responseCode });
        }
      }

      await page.waitForLoadState('domcontentloaded');
      await this._waitNetworkIdle(page, id, url);

      // Adapt viewport height to scroll height
      await pages.adjustViewportToPage(page, optionsViewportAdjust);
      await page.waitForTimeout(3000);
      await this._waitNetworkIdle(page, id, url);

      // Take snapshot
      await pages.takeSnapshot(page, optionsSnapshot).catch(error => {
        log.error({ err: error, err_msg: error.message.split("\n")[0], id: id, url: url }, "error with snapshotting (promise)");
        // Not sure what to do here?
        // (a) Keep and continue with half results,
        // (b) Delete possible results and abort for URL ?
      });

      // Remove invisible elements
      if (optionsSnapshot.domCleaned !== undefined && optionsSnapshot.domCleaned !== false) {
        await this._removeInvisibleElements(page, id, url);
        await pages.takeDomSnapshot(page, { path: path.join(optionsSnapshot.path, optionsSnapshot.domCleaned.defaultName) }).catch(error => {
          log.error({ err: error, err_msg: error.message.split("\n")[0], id: id, url: url }, "error with snapshotting (promise) (domCleaned)");
        });
      }

      return true;
    } catch (error) {
      log.error({ err: error, err_msg: error.message.split("\n")[0], id: id, url: url }, "error with snapshotting");
      return false;
    }
  }

  async _writeStatus(path, data = {}) {
    fs.mkdirsSync(path);
    fs.writeJsonSync(path.join(path, "status.json"), data);
  }

  /**
   * Wait for `'networkidle'` state on `page`. Catch possible errors.
   * @param {Page} page - A Playwright {@link https://playwright.dev/docs/api/class-page|Page} object
   * @param {string} id - the URL id (for logging purposes)
   * @param {string} url - the page url (for logging purposes)
   */
  async _waitNetworkIdle(page, id, url) {
    try {
      await page.waitForLoadState('networkidle');
    } catch (error) {
      log.warn({ id: id, url: url, err_msg: error.message.split("\n")[0] }, "page.waitForLoadState('networkidle')")
    }
  }

  /**
   * Remove invisible elements from the page.
   * @param {Page} page - A Playwright {@link https://playwright.dev/docs/api/class-page|Page} object
   * @param {string} id - the URL id (for logging purposes)
   * @param {string} url - the page url (for logging purposes)
   */
  async _removeInvisibleElements(page, id, url) {
    const size_before = (await page.content()).length;
    // see `pages.takeNodesSnapshot()`
    await page.evaluate(() => {
      const isVisible = (element) => {
        // https://stackoverflow.com/a/33456469
        return !!(element.offsetWidth || element.offsetHeight || element.getClientRects().length);
      };

      const traverse = (node) => {
        if (node.nodeType === Node.ELEMENT_NODE) {
          if (!isVisible(node)) {
            node.remove();
          } else {
            const children = node.childNodes;
            for (let c = children.length - 1; c >= 0; --c) {
              const child = children[c];
              if (child.nodeType === Node.ELEMENT_NODE || child.nodeType === Node.TEXT_NODE) {
                traverse(child);
              }
            }
          }
        }
      };

      traverse(document.getElementsByTagName("body")[0]);
    });
    const size_after = (await page.content()).length;
    log.warn({ id: id, url: url, size_before: size_before, size_after: size_after }, "_removeInvisibleElements")
  }
};
```
</details>

<details>
  <summary>config.js</summary>

```json
{"urls": [
  {"id": 2, "url": "http://tenchimuyotranslationblog.blogspot.com/2017/03/gxp-4.html"}
]}
```
</details>

```bash
# just mount the script and input folders, output can be ignored
docker run -it --rm --volume $(pwd):/script:ro --volume $(pwd):/input:ro ghcr.io/webis-de/scriptor:latest --no-tracing --no-har --no-warc
```

Ok. The `takeScreenshot` errors were unfortunately only reproducible for this one URL above. Not sure whether the repeated _new tab -> page load -> screenshot -> close tab -> repeat_ process may have influenced this but for ~13 other URLs it worked.

<details>
  <summary>Kubernetes Log</summary>

```json
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"options":{"scriptDirectory":"/script","outputDirectory":"/output","har":false,"tracing":false,"warc":false},"runOptions":{"har":false,"tracing":false,"warc":false},"msg":"cli.getRunOptions","time":"2022-01-13T13:59:50.197Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"runOptions":{"har":false,"insecure":false,"proxy":false,"replay":"not","showBrowser":false,"tracing":false,"unrandomize":"constant","video":false,"warc":false},"msg":"scripts.run.options","time":"2022-01-13T13:59:50.199Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"scriptDirectory":"/script","msg":"scripts.instantiate","time":"2022-01-13T13:59:50.201Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"scriptDirectory":"/script","msg":"scripts.source","time":"2022-01-13T13:59:50.201Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"scriptModule":"/script/Script","scriptFile":"/script/Script.js","msg":"scripts.source.execute","time":"2022-01-13T13:59:50.201Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"msg":"scripts.source.executed","time":"2022-01-13T13:59:50.209Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"msg":"scripts.instantiate.execute","time":"2022-01-13T13:59:50.209Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"scriptName":"Snapshot-Novelupdates","version":"0.1.0","msg":"Script.construct","time":"2022-01-13T13:59:50.209Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"msg":"scripts.instantiate.executed","time":"2022-01-13T13:59:50.210Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"contextNames":["default"],"msg":"scripts.instantiateBrowserContexts.names","time":"2022-01-13T13:59:50.211Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"contextName":"default","scriptDirectory":"/script","inputDirectory":"/input","browserContextOptions":{"viewport":{"width":1280,"height":720}},"msg":"scripts.instantiateBrowserContext.options.read","time":"2022-01-13T13:59:50.212Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"contextName":"default","browserType":"chromium","browserContextOptions":{"viewport":{"width":1280,"height":720}},"outputUserDataDirectory":"/output/browserContexts/default/userData","runOptions":{"har":false,"insecure":false,"proxy":false,"replay":"not","showBrowser":false,"tracing":false,"unrandomize":"constant","video":false,"warc":false},"msg":"scripts.instantiateBrowserContext.options.final","time":"2022-01-13T13:59:50.215Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"msg":"scripts.startUnrandomize.constant","time":"2022-01-13T13:59:50.583Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"msg":"scripts.instantiateBrowserContext.done","time":"2022-01-13T13:59:50.587Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"contextNames":["default"],"msg":"scripts.run","time":"2022-01-13T13:59:50.587Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"options":{"viewportAdjust":{},"snapshot":{"nodes":{"addElementText":false,"addCss":false,"addAttributes":false},"viewport":false,"domCleaned":{"defaultName":"dom-cleaned.html"}},"failNon2XX":true,"urls":[{"id":0,"url":"http://tenchimuyotranslationblog.blogspot.com/2017/03/gxp-4.html"}]},"msg":"script.options","time":"2022-01-13T13:59:50.930Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"msg":"Processing 1 urls.","time":"2022-01-13T13:59:50.931Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"id":"0","url":"http://tenchimuyotranslationblog.blogspot.com/2017/03/gxp-4.html","msg":"snapshot","time":"2022-01-13T13:59:50.974Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"old":{"width":1280,"height":720},"new":{"width":1280,"height":209862},"msg":"pages.adjustViewportToPage","time":"2022-01-13T13:59:57.736Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":40,"id":"0","url":"http://tenchimuyotranslationblog.blogspot.com/2017/03/gxp-4.html","err_msg":"page.waitForLoadState: Timeout 10000ms exceeded.","msg":"page.waitForLoadState('networkidle')","time":"2022-01-13T14:00:10.786Z","v":0}
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

page.screenshot: Timeout 10000ms exceeded.
    at takeScreenshot (/scriptor/lib/pages.js:450:15)
    at Object.takeSnapshot (/scriptor/lib/pages.js:259:22)
    at module.exports._processOne (/script/Script-multi.js:115:19)
    at async module.exports.run (/script/Script-multi.js:54:24)
    at async Object.run (/scriptor/lib/scripts.js:64:31) {
  name: 'TimeoutError'
}
```
</details>

As can be seen from the log, the timeout from `page.waitForLoadState('networkidle')` in my `_waitNetworkIdle` is caught without issues ... (Happened for some of the other URLs, too.)
~~Might this be a reason that the screenshot fails because the screenshotting is also waiting for some state where the webpage does not change?~~

---

**Minimal**: with the default script (30s timeout). But there is also no try-catch involved.
```bash
docker run -it --rm ghcr.io/webis-de/scriptor:latest --no-tracing --no-har --no-warc --input "{\"url\":\"http://tenchimuyotranslationblog.blogspot.com/2017/03/gxp-4.html\"}"
```
<details>
  <summary>Output</summary>

```js
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"directory":"/tmp/scriptor-input-qAiiqh","config":{"url":"http://tenchimuyotranslationblog.blogspot.com/2017/03/gxp-4.html"},"msg":"cli.getInputDirectory.makeTemporaryInputDirectory","time":"2022-01-13T14:12:32.244Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"options":{"scriptDirectory":"/script","outputDirectory":"/output","har":false,"tracing":false,"warc":false,"input":"{\"url\":\"http://tenchimuyotranslationblog.blogspot.com/2017/03/gxp-4.html\"}"},"runOptions":{"har":false,"tracing":false,"warc":false},"msg":"cli.getRunOptions","time":"2022-01-13T14:12:32.248Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"runOptions":{"har":false,"insecure":false,"proxy":false,"replay":"not","showBrowser":false,"tracing":false,"unrandomize":"constant","video":false,"warc":false},"msg":"scripts.run.options","time":"2022-01-13T14:12:32.248Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"scriptDirectory":"/script","msg":"scripts.instantiate","time":"2022-01-13T14:12:32.249Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"scriptDirectory":"/script","msg":"scripts.source","time":"2022-01-13T14:12:32.250Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"scriptModule":"/script/Script","scriptFile":"/script/Script.js","msg":"scripts.source.execute","time":"2022-01-13T14:12:32.250Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"msg":"scripts.source.executed","time":"2022-01-13T14:12:32.256Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"msg":"scripts.instantiate.execute","time":"2022-01-13T14:12:32.256Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"scriptName":"Snapshot","version":"0.1.0","msg":"Script.construct","time":"2022-01-13T14:12:32.256Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"msg":"scripts.instantiate.executed","time":"2022-01-13T14:12:32.257Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"contextNames":["default"],"msg":"scripts.instantiateBrowserContexts.names","time":"2022-01-13T14:12:32.258Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"contextName":"default","scriptDirectory":"/script","inputDirectory":"/tmp/scriptor-input-qAiiqh","browserContextOptions":{"viewport":{"width":1280,"height":720}},"msg":"scripts.instantiateBrowserContext.options.read","time":"2022-01-13T14:12:32.260Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"contextName":"default","browserType":"chromium","browserContextOptions":{"viewport":{"width":1280,"height":720}},"outputUserDataDirectory":"/output/browserContexts/default/userData","runOptions":{"har":false,"insecure":false,"proxy":false,"replay":"not","showBrowser":false,"tracing":false,"unrandomize":"constant","video":false,"warc":false},"msg":"scripts.instantiateBrowserContext.options.final","time":"2022-01-13T14:12:32.264Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"msg":"scripts.startUnrandomize.constant","time":"2022-01-13T14:12:32.686Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"msg":"scripts.instantiateBrowserContext.done","time":"2022-01-13T14:12:32.690Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"contextNames":["default"],"msg":"scripts.run","time":"2022-01-13T14:12:32.690Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"options":{"viewportAdjust":{},"url":"http://tenchimuyotranslationblog.blogspot.com/2017/03/gxp-4.html"},"msg":"script.options","time":"2022-01-13T14:12:32.691Z","v":0}
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":30,"old":{"width":1280,"height":720},"new":{"width":1280,"height":209862},"msg":"pages.adjustViewportToPage","time":"2022-01-13T14:12:39.898Z","v":0}
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

page.screenshot: Timeout 30000ms exceeded.
    at takeScreenshot (/scriptor/lib/pages.js:450:15)
    at Object.takeSnapshot (/scriptor/lib/pages.js:259:22)
    at module.exports.run (/script/Script.js:50:17)
    at async Object.run (/scriptor/lib/scripts.js:64:31) {
  name: 'TimeoutError'
}
```
</details>

**Comment by Querela** [comment]
Ok, minimal Script (2 changes):

<details>
<summary>Minimal script</summary>

Based on: https://github.com/webis-de/scriptor/blob/bfbc8c9d824d2a08c7c526b2b83ec5e061be9f84/scripts/Snapshot-0.1.0/Script.js
See `EDIT:` comments.

```js
const fs = require("fs-extra");
const path = require('path');

const { AbstractScriptorScript, files, pages, log } = require('@webis-de/scriptor');

const NAME = "Snapshot";
const VERSION = "0.2.0";

const SCRIPT_OPTION_URL = "url";
const SCRIPT_OPTIONS_VIEWPORT_ADJUST = "viewportAdjust";
const SCRIPT_OPTIONS_SNAPSHOT = "snapshot";

module.exports = class extends AbstractScriptorScript {

  constructor() {
    super(NAME, VERSION);
  }

  async run(browserContexts, scriptDirectory, inputDirectory, outputDirectory) {
    const browserContext = browserContexts[files.BROWSER_CONTEXT_DEFAULT];
    browserContext.setDefaultTimeout(10000); // EDIT: global page function timeout

    // Script options
    const defaultScriptOptions = { viewportAdjust: {} };
    const requiredScriptOptions = [SCRIPT_OPTION_URL];
    const scriptOptions = files.readOptions(files.getExisting(
      files.SCRIPT_OPTIONS_FILE_NAME, [scriptDirectory, inputDirectory]),
      defaultScriptOptions, requiredScriptOptions);
    log.info({ options: scriptOptions }, "script.options");
    fs.writeJsonSync( // document options
      path.join(outputDirectory, files.SCRIPT_OPTIONS_FILE_NAME), scriptOptions);

    const url = scriptOptions[SCRIPT_OPTION_URL];
    const optionsViewportAdjust = scriptOptions[SCRIPT_OPTIONS_VIEWPORT_ADJUST];
    const optionsSnapshot = Object.assign(
      { path: path.join(outputDirectory, "snapshot") },
      scriptOptions[SCRIPT_OPTIONS_SNAPSHOT]);

    // Load page
    const page = await browserContext.newPage();
    await page.goto(url);
    await page.waitForLoadState('domcontentloaded');
    await page.waitForLoadState('networkidle');

    // Adapt viewport height to scroll height
    await pages.adjustViewportToPage(page, optionsViewportAdjust);
    await page.waitForTimeout(1000);
    await page.waitForLoadState('networkidle');

    // Take snapshot
    // EDIT: wrap try/catch, according to https://playwright.dev/docs/api/class-timeouterror
    // NOTE: error message says node context
    try {
      await pages.takeSnapshot(page, optionsSnapshot);
    } catch (error) {
      if (error instanceof playwright.errors.TimeoutError) {
        console.log("Timeout!")
      } else {
        console.log("Other Error:", error.message)
      }
    }
    return true;
  }
};
```
</details>

<details>
<summary>Some other error catching, not on my side: (3-5 sec timeout)</summary>

```json
{"name":"scriptor","hostname":"scriptor-with-ceph","pid":1,"level":60,"err":{"message":"page.goto: Timeout 5000ms exceeded.\n=========================== logs ===========================\nnavigating to \"http://tenchimuyotranslationblog.blogspot.com/2017/03/gxp-4.html\", waiting until \"load\"\n============================================================","name":"TimeoutError","stack":"page.goto: Timeout 5000ms exceeded.\n=========================== logs ===========================\nnavigating to \"http://tenchimuyotranslationblog.blogspot.com/2017/03/gxp-4.html\", waiting until \"load\"\n============================================================\n    at module.exports.run (/script/Script.js:41:16)\n    at async Object.run (/scriptor/lib/scripts.js:64:31)"},"msg":"page.goto: Timeout 5000ms exceeded.\n=========================== logs ===========================\nnavigating to \"http://tenchimuyotranslationblog.blogspot.com/2017/03/gxp-4.html\", waiting until \"load\"\n============================================================","time":"2022-01-13T14:34:17.028Z","v":0}
```
</details>

<details>
<summary>Screenshot error, 10 sec timeout:</summary>

```js
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

page.screenshot: Timeout 5000ms exceeded.
    at takeScreenshot (/scriptor/lib/pages.js:450:15)
    at Object.takeSnapshot (/scriptor/lib/pages.js:259:22)
    at module.exports.run (/script/Script.js:52:19)
    at async Object.run (/scriptor/lib/scripts.js:64:31) {
  name: 'TimeoutError'
}
```
</details>

```bash
docker run -it --rm --volume $(pwd):/script:ro ghcr.io/webis-de/scriptor:latest --no-tracing --no-har --no-warc --input "{\"url\":\"http://tenchimuyotranslationblog.blogspot.com/2017/03/gxp-4.html\"}"
```

**Comment by johanneskiesel** [comment]
Ok, on a first test this looks like it works: https://github.com/webis-de/scriptor/commit/84b74f8dc79fc96cab97a9c77db2ab25169fea19

So maybe you can try v0.6.5?

I hope I did not break anything else... I really need some unit tests.

**Comment by johanneskiesel** [comment]
Based on private communication, this seems to work now
